apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: "sample-validating-webhook"
webhooks:
  - name: "sample-validating-webhook.hoge.fuga.local"
    namespaceSelector:
      matchExpressions:
        - key: kubernetes.io/metadata.name
          operator: In
          values: ["webhook-tutorial-system"]
    failurePolicy: Fail
    rules:
      - apiGroups: [""]
        operations: ["CREATE"]
        apiVersions: ["v1"]
        resources: ["pods"]
        scope: "Namespaced"
    clientConfig:
      #    caBundle:
      service:
        namespace: webhook-tutorial-system
        name: mytest-service
        path: /my-validation
    admissionReviewVersions: ["v1"]
    timeoutSeconds: 5
    sideEffects: None
