apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev-ssh-sidecar

resources:
  - ns.yaml
  - pod.yaml
  - sa.yaml
  - svc.yaml

images:
  - name: busybox
    newTag: 1.36.1
  - name: golang
    newTag: 1.22-rc
