apiVersion: v1
kind: Pod
metadata:
  name: dev-ssh-sidecar
  labels:
    app: dev-ssh-sidecar
spec:
  serviceAccountName: ssh-sidecar
  #automountServiceAccountToken: false
  containers:
    - name: test-container
      image: busybox
      command: ["/bin/sh", "-c"]
      args:
        - echo 'test pod'; sleep 'infinity'
      resources:
        limits:
          memory: "128Mi"
          cpu: "100m"
      imagePullPolicy: IfNotPresent
    - name: dev-golang
      image: golang
      command:
        - sleep
        - "infinity"
      resources:
        limits:
          memory: "2Gi"
          cpu: "1"
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 22
      env:
        - name: SSH_PUB_KEY
          value: <INPUT_SSH_PUB_KEY>
        - name: TARGET_CONTAINER
          value: test-container
        - name: PORT
          value: "22"
        - name: SHELL
          value: sh
      volumeMounts:
        - name: code-volume
          mountPath: /code
      workingDir: /code
  volumes:
    - name: code-volume
      hostPath:
        path: <INPUT_CODE_DIR>
