apiVersion: v1
kind: ServiceAccount
metadata:
  name: ssh-sidecar
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pod-executer-role
rules:
  - apiGroups: [""] # "" はコアのAPIグループを示します
    resources: ["pods"]
    verbs: ["get"] #["watch", "list"]
  - apiGroups: [""]
    resources: ["pods/exec"]
    verbs: ["create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ssh-sidecar-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: pod-executer-role
subjects:
  - apiGroup: ""
    kind: ServiceAccount
    name: ssh-sidecar
